### ISSUE TITLE
Crate-O Documentation for LDaCA website

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#123]
Checklist of items to include (not in specific order):

- [ ] FAQ
- [x] General summary
- [x] Language Data Commons specific https://github.com/Language-Research-Technology/ro-crate-editor-profiles/blob/help_docs/help/modes/language-data-commons.md
- [x] Schema specific: https://github.com/Language-Research-Technology/ro-crate-editor-profiles/blob/help_docs/help/modes/schema.md
- [x] link to or include the explainer on SOSSs
- [x] ldaca.edu.au/docs - Something? Tell Moises 😄 

Reference for summary from Alvin:
Mode file:  just a json file that can be loaded to crate-o at run time. Can be anywhere but having all of them in one place make things easier to find and load
Mode file validator: a library (js code) to validate a mode file.
Crate validators: a library that uses various rules (a mode file among others) to validate a crate.
Mode file generator: a library to programmatically generate a mode file.
Profile generator: a library to generate profile documents

**Comment by rosanna-smith** [comment]
Any other ones to add at this stage, @ptsefton?

**Comment by ptsefton** [comment]
also link to or include the explainer on SOSSs

**Comment by rosanna-smith** [comment]
@moisbo When the documentation is up it'll be at https://www.ldaca.edu.au/resources/user-guides/crate-o/

**Comment by moisbo** [comment]
Is this for replacement https://docs.ldaca.edu.au ? because it looks like this is only for crate-o?

**Comment by rosanna-smith** [comment]
As far as I know, we're not planning on using https://docs.ldaca.edu.au/ for any of the user guide pages. @smusgrav to confirm

**Comment by moisbo** [comment]
No worries, just because the data.ldaca.edu.au points to there and if you are creating one that is not empty like this one I can quickly update it

**Comment by rosanna-smith** [comment]
The website now has general information, basic navigation and RO-Crate creation in Crate-O (using a spreadsheet to upload data underway).
Would docs on SOSS generation and creating schemas/profiles/modes be better to stay in the relevant repo docs rather than the website?
@ptsefton

**Comment by ptsefton** [comment]
Yep – that detail is for implementers so it should be on those repos I think

--


From: Rosanna ***@***.***>
Date: Friday, 21 June 2024 at 9:53 am
To: Language-Research-Technology/crate-o ***@***.***>
Cc: Peter Sefton ***@***.***>, Mention ***@***.***>
Subject: Re: [Language-Research-Technology/crate-o] Crate-O Documentation for LDaCA website (Issue #123)

The website now has general information, basic navigation and RO-Crate creation in Crate-O (using a spreadsheet to upload data underway).
Would docs on SOSS generation and creating schemas/profiles/modes be better to stay in the relevant repo docs rather than the website?
@ptsefton<https://github.com/ptsefton>
