### ISSUE TITLE
Always show help text rather than only on hover

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#78]
Similar to describo, this might help with some of the metadata where the actual use differs from what users might initially expect. We could have an option to hide the help text if users don't want to view it anymore.

**Comment by ptsefton** [comment]
Lets try it with help text jsut ON for now -- under very property that's editable

**Comment by moisbo** [comment]
This is how it would look... Is that OK? I think we removed it because it takes too much room

<img width="1725" alt="Screenshot 2023-09-28 at 11 21 05 am" src="https://github.com/Language-Research-Technology/crate-o/assets/2850269/de88f1e5-1fd6-4fe6-9fa6-c61d939c0596">

<img width="1725" alt="Screenshot 2023-09-28 at 11 23 27 am" src="https://github.com/Language-Research-Technology/crate-o/assets/2850269/c77c6a72-6269-4ec8-b7e3-8faba5ebc9db">

**Comment by moisbo** [comment]
Ok commented on slack and we'll keep as above
